server.servlet.context-path=/payment
spring.boot.admin.client.url=http://localhost:1414
#Mongodb
spring.mongodb.database=soumikdb
spring.mongodb.port=27017
spring.mongodb.host=localhost
spring.data.mongodb.socket-timeout=30000
