server.servlet.context-path=/telusko

spring.data.mongodb.socket-timeout=30000
spring.data.mongodb.database=soumikdb
spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


